apiVersion: apps/v1
kind: Deployment
metadata:
  name: prt-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prt
  template:
    metadata:
      labels:
        app: prt
    spec:
      containers:
      - name: prt-container
        image: kjrashmi20/prt-app:latest
        ports:
        - containerPort: 80
